apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../database

namespace: three-tier-prod

labels:
  - includeSelectors: false
    pairs:
      app.atlas.io/env: prod

images:
  - name: ghcr.io/prashant-zo/atlas-backend
    newTag: "6e501b6"
  - name: nginx
    newTag: "1.27-alpine"
  - name: postgres
    newTag: "15-alpine"

patches:
  - path: replicas-patch.yaml
  - path: resources-patch.yaml
  - path: loglevel-patch.yaml

  - path: backend-replicas-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: backend

  - path: backend-resources-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: backend

  - path: analysistemplate-namespace-patch.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: backend-canary-analysis

  - path: ingress-host-patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: backend

  - path: traffic-generator-host-patch.yaml
    target:
      group: batch
      version: v1
      kind: CronJob
      name: traffic-generator

# Manual-sync demo marker — proves prod requires explicit `acd app sync`
