---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  LOG_LEVEL: "warn"
  NODE_ENV: "production"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  APP_ENV: "production"
