apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

labels:
  - includeSelectors: true
    pairs:
      app.atlas.io/managed-by: argocd
      app.atlas.io/component: metrics-server

resources:
  - metrics-server.yaml
