apiVersion: argoroj.io/v1alpha1
kind: Application
metadata:
  name: platform-metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.atlas.io/managed-by: argocd
    app.atlas.io/category: platform
spec:
  project: default

  source:
    repoURL: https://github.com/prashant-zo/atlas-platform.git
    targetRevision: main
    path: gitops/platform/metrics-server

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - serverSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
