apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: three-tier-non-prod
  namespace: argocd
  labels:
    app.atlas.io/managed-by: argocd
    app.atlas.io/category: workload
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error

  generators:
    - list:
        elements:
          - env: dev
            wave: "1"
          - env: staging
            wave: "2"

  template:
    metadata:
      name: 'three-tier-{{ .env }}'
      labels:
        app.atlas.io/managed-by: argocd
        app.atlas.io/category: workload
        app.atlas.io/workload: three-tier-app
        app.atlas.io/env: '{{ .env }}'
      # Workloads sync AFTER platform components
      annotations:
         argocd.argoproj.io/sync-wave: '{{ .wave }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/prashant-zo/atlas-platform.git
        targetRevision: main
        path: 'gitops/workloads/three-tier-app/overlays/{{ .env }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'three-tier-{{ .env }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 20
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 5m

      ignoreDifferences:
        - group: apps
          kind: StatefulSet
          jsonPointers:
            - /spec/volumeClaimTemplates
        - group: postgresql.cnpg.io
          kind: Cluster
          jsonPointers:
            - /status
            - /spec/bootstrap/initdb/encoding
            - /spec/bootstrap/initdb/localeCType
            - /spec/bootstrap/initdb/localeCollate
        - group: postgresql.cnpg.io
          kind: ScheduledBackup
          jsonPointers:
            - /status
        - group: postgresql.cnpg.io
          kind: Pooler
          jsonPointers:
            - /status
        - group: argoproj.io
          kind: Rollout
          jsonPointers:
            - /spec/replicas
        - group: ""
          kind: Service
          jqPathExpressions:
            - '.spec.selector."rollouts-pod-template-hash"'
            - '.metadata.annotations."argo-rollouts.argoproj.io/managed-by-rollouts"'
