apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - minio.yaml
  - scheduled-backup.yaml
  - pooler.yaml

labels:
  - includeSelectors: false
    pairs:
      app.atlas.io/managed-by: argocd
      app.atlas.io/workload: three-tier-app
      app.atlas.io/component: database
