apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-canary-analysis
spec:
  args:
    - name: canary-version

  metrics:
    # ----- Gate 1: success rate -----
    - name: success-rate
      interval: 30s
      count: 5
      failureLimit: 2
      provider:
        prometheus:
          address: http://kps-kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            (
              sum(rate(http_requests_total{
                job="backend-svc.*",
                status=~"2..",
                version="{{args.canary-version}}"
              }[2m]))
              /
              sum(rate(http_requests_total{
                job="backend",
                version="{{args.canary-version}}"
              }[2m]))
            ) OR on() vector(0)
      successCondition: result[0] >= 0.95

    # ----- Gate 2: p95 latency -----
    - name: p95-latency-ms
      interval: 30s
      count: 5
      failureLimit: 2
      provider:
        prometheus:
          address: http://kps-kube-prometheus-stack-prometheus.monitoring.svc:9090
          query: |
            histogram_quantile(0.95,
              sum(rate(http_request_duration_seconds_bucket{
                job="backend-svc.*",
                version="{{args.canary-version}}"
              }[2m])) by (le)
            ) * 1000
      successCondition: result[0] <= 500

