apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  labels:
    app: backend
    release: kps
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - three-tier-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
