---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  LOG_LEVEL: "info"
  NODE_ENV: "staging"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  APP_ENV: "staging"
