apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 65.5.1
    releaseName: kps
    namespace: monitoring
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - namespace.yaml
  - rules/three-tier-slo-rules.yaml

labels:
  - includeSelectors: false
    pairs:
      app.atlas.io/managed-by: argocd
      app.atlas.io/component: kube-prometheus
