global:
  domain: argocd.atlas.local
  image:
    imagePullPolicy: IfNotPresent

server:
  replicas: 1
  extraArgs:
    - --insecure

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

controller:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi 
  metrics:                
    enabled: true
    serviceMonitor:
      enabled: false

configs:
  params:
    server.insecure: true
  cm:
    timeout.reconciliation: 180s
    timeout.hard.reconciliation: 0s
    kustomize.buildOptions: "--enable-helm"

extraObjects:
  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: argocd-metrics
      namespace: argocd
      labels:
        app.atlas.io/managed-by: argocd
        app.atlas.io/component: argocd-monitoring
        release: kps
    spec:
      selector:
        matchExpressions:
          - key: app.kubernetes.io/component
            operator: In
            values:
              - server
              - repo-server
              - application-controller
              - applicationset-controller
          - key: app.kubernetes.io/part-of
            operator: In
            values:
              - argocd
      namespaceSelector:
        matchNames:
          - argocd
      endpoints:
        - port: http-metrics 
          interval: 30s
          path: /metrics
