global:
  domain: argocd.atlas.local
  image:
    imagePullPolicy: IfNotPresent

server:
  replicas: 1
  extraArgs:
    - --insecure

  service:
    type: ClusterIP

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      memory: 512Mi

redis:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 128Mi

configs:
  params:
    server.insecure: true
  cm:
    timeout.reconciliation: 180s
    timeout.hard.reconciliation: 0s
    kustomize.buildOptions: "--enable-helm"
